services:

  apiserver:
    image: apiserver
    container_name: apiserver
    hostname: apiserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - ./:/code
    environment:
      DB_URL: sqlite:///database.db
    networks:
      dorsnet:
        ipv4_address: 172.28.2.2

  dors-ui:
    image: dors-ui
    container_name: dors-ui
    hostname: dors-ui
    build:
      context: ./app-ui
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://172.28.2.2:8000
    restart: unless-stopped
    ports:
      - 80:3000
    depends_on:
      - apiserver
    networks:
      dorsnet:
        ipv4_address: 172.28.2.3


networks:
  dorsnet:
    # driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
